trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'wordpress'
  appName: 'wordpress-live'
  resourceGroup: 'wordpresslc'
  packagePath: '$(Build.ArtifactStagingDirectory)/wordpress.zip'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/wordpress.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    resourceGroupName: '$(resourceGroup)'
    package: '$(packagePath)'